### PR TITLE
Add support for 0.15.x

### PR DESCRIPTION
**Pull request by william-saxton**
When updating terraform to version 0.15 and above the defaults for the "init" command changed. This update removed deprecated arguments from the defaults in the module.

Also updated eslint to allow windows users to contribute to the repo, code from @frasdav.

### CODE REVIEW

**Comment by frasdav** [comment]
Only other thing that's been removed in 0.15 that this code references is `-var` and `-var-file` in `terraform validate` - could you `ifVersionSatisfies` those in `templates/validate.hbs` too, pls?

**Comment by frasdav** [comment]
Ignore me, already done.

**Comment by frasdav** [comment]
> Only other thing that's been removed in 0.15 that this code references is `-var` and `-var-file` in `terraform validate` - could you `ifVersionSatisfies` those in `templates/validate.hbs` too, pls?

Ignore me, already done.

**Review by CDA0 — APPROVED** [review]
looks good to me from the help of 0.15

**Pull request merged**
