### PR TITLE
Update show command

### PR DESCRIPTION
**Pull request by leovafme**
remove module-depth and add json in template command based in https://www.terraform.io/docs/cli/commands/show.html

### CODE REVIEW

**Comment by kitforbes** [comment]
Hi @leovafme, thank you for the contribution. Can I ask which version of Terraform you're using? We may need to update this template to support different versions.

**Comment by leovafme** [comment]
I use Terraform v0.14.9 
with module-depth
imagen

replace module-depth per json
imagen

**Comment by kitforbes** [comment]
Thanks. We've not gone through the commands to update them for v0.14 or v0.15 as we are primarily working with v0.11 and v0.13 right now. There are likely other commands that need to be updated. I won't ask you to do that for us, but could you update your PR to use a switch statement for this specific command? An example of it can be seen here: https://github.com/CDA0/terrajs/blob/52a885166efb82d21566e4b8d8b53acbe928dacb/templates/validate.hbs#L3-L12

**Comment by leovafme** [comment]
this implementation valid?, add ifmajor helper to work on higher versions

**Comment by kitforbes** [comment]
I like it. It made me rethink how I previously implemented the version checks. I created #27 which should make it much easier for you (once reviewed/merged) to declare version requirements in templates going forward. Something like this would work (assuming no changes are needed):
```hbs
{{command}} show
{{#ifVersionSatisfies version '<0.12'}}
{{> module-depth }}
{{else}}
{{> json }}
{{/ifVersionSatisfies}}
{{> no-color }}
{{dir}}
```

**Comment by leovafme** [comment]
#27 it is a very good solution. thx

**Review by kitforbes — APPROVED** [review]
Great stuff. We'll release a new version shortly once a few more changes are in.

**Pull request merged**
